# Generated by Django 4.2 on 2026-01-10 17:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='descritpion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголвок'),
        ),
    ]
